#!/bin/sh 

nlynx api orgs create name='Wisconsin Watch' timezone='US/Central'
nlynx api recipes update id=1 feed_url='http://wisconsinwatch.org/feed/'
nlynx api recipes cook id=1 
nlynx api recipes update id=9 
nlynx api recipes cook id=9
nlynx api recipes update id=3 screen_name='WisWatch'
